---
# IMPORTANT: Change settings here, but DO NOT change the spacing.
# Remove comments and add values where applicable.
# The descriptions below should be self-explanatory

title: "Question 3"
#subtitle: "This will appear as Right Header"

documentclass: "elsarticle"

# --------- Thesis title (Optional - set to FALSE by default).
# You can move the details below around as you please.
Thesis_FP: FALSE
# Entry1: "An unbelievable study with a title spanning multiple lines."
# Entry2: "\\textbf{Some Guy}" # textbf for bold
# Entry3: "A thesis submitted toward the degree of Doctor of Philosophy"
# Uni_Logo: Tex/Logo.png # Place a logo in the indicated location (from your root, e.g. defaults to ~/Tex/Logo.png) and uncomment this line. Leave uncommented for no image
# Logo_width: 0.3 # If using a logo - use this to set width (size) of image
# Entry4: "Under the supervision of: \\vfill Prof. Joe Smith and Dr. Frank Smith"
# Entry5: "Stellenbosch University"
# Entry6: April 2020
# Entry7:
# Entry8:

# --------- Front Page
# Comment: ----- Follow this pattern for up to 5 authors
AddTitle: TRUE # Use FALSE when submitting to peer reviewed platform. This will remove author names.
Author1: "Wesley James Williams"  # First Author - note the thanks message displayed as an italic footnote of first page.
Ref1: "Stellenbosch University, South Africa" # First Author's Affiliation
Email1: "21691126\\@sun.ac.za" # First Author's Email address

# Author2: "John Smith"
# Ref2: "Some other Institution, Cape Town, South Africa"
# Email2: "John\\@gmail.com"
# CommonAffiliation_12: TRUE # If Author 1 and 2 have a common affiliation. Works with _13, _23, etc.
# 
# Author3: "John Doe"
# Email3: "Joe\\@gmail.com"

CorrespAuthor_1: TRUE  # If corresponding author is author 3, e.g., use CorrespAuthor_3: TRUE

# Comment out below to remove both. JEL Codes only given if keywords also given.
# keywords: "Multivariate GARCH \\sep Kalman Filter \\sep Copula" # Use \\sep to separate
# JELCodes: "L250 \\sep L100"

# ----- Manage headers and footers:
#BottomLFooter: $Title$
#BottomCFooter:
#TopLHeader: \leftmark # Adds section name at topleft. Remove comment to add it.
BottomRFooter: "\\footnotesize Page \\thepage" # Add a '#' before this line to remove footer.
addtoprule: TRUE
addfootrule: TRUE               # Use if footers added. Add '#' to remove line.

# --------- page margins:
margin: 2.3 # Sides
bottom: 2 # bottom
top: 2.5 # Top
HardSet_layout: TRUE # Hard-set the spacing of words in your document. This will stop LaTeX squashing text to fit on pages, e.g.
# This is done by hard-setting the spacing dimensions. Set to FALSE if you want LaTeX to optimize this for your paper.

# --------- Line numbers
linenumbers: FALSE # Used when submitting to journal

# ---------- References settings:
# You can download cls format here: https://www.zotero.org/ - simply search for your institution. You can also edit and save cls formats here: https://editor.citationstyles.org/about/
# Hit download, store it in Tex/ folder, and change reference below - easy.
bibliography: Tex/ref.bib       # Do not edit: Keep this naming convention and location.
csl: Tex/harvard-stellenbosch-university.csl # referencing format used.
# By default, the bibliography only displays the cited references. If you want to change this, you can comment out one of the following:
#nocite: '@*' # Add all items in bibliography, whether cited or not
# nocite: |  # add specific references that aren't cited
#  @grinold2000
#  @Someoneelse2010

# ---------- General:
RemovePreprintSubmittedTo: TRUE  # Removes the 'preprint submitted to...' at bottom of titlepage
Journal: "Financial Econometrics 871"   # Journal that the paper will be submitting to, if RemovePreprintSubmittedTo is set to TRUE.
toc: FALSE                       # Add a table of contents
numbersections: TRUE             # Should sections (and thus figures and tables) be numbered?
fontsize: 12pt                  # Set fontsize
linestretch: 1.2                # Set distance between lines.
link-citations: TRUE            # This creates dynamic links to the papers in reference list.

### Adding additional latex packages:
# header-includes:
#    - \usepackage{colortbl} # Add additional packages here.

output:
  pdf_document:
    keep_tex: TRUE
    template: Tex/TexDefault.txt
    fig_width: 3.5 # Adjust default figure sizes. This can also be done in the chunks of the text.
    fig_height: 3.5
abstract: |
  Answers the Question
---

<!-- First: Set your default preferences for chunk options: -->

<!-- If you want a chunk's code to be printed, set echo = TRUE. message = FALSE stops R printing ugly package loading details in your final paper too. I also suggest setting warning = FALSE and checking for warnings in R, else you might find ugly warnings in your paper. -->

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE, fig.width = 6, fig.height = 5, fig.pos="H", fig.pos = 'H')

library(tidyverse)
library(tbl2xts)
library(rmsfuns)
library(fmxdat)
#Source in all the code from the code file
list.files('code/', full.names = T, recursive = T) %>% .[grepl('.R', .)] %>% as.list() %>% walk(~source(.))

#read in the data
ALSI <- read_rds("data/ALSI.rds")
RebDays <- read_rds("data/Rebalance_days.rds")
ZAR <- read_rds("data/Monthly_zar.rds")
swix <- read_rds("data/Capped_SWIX.rds")


```


<!-- ############################## -->
<!-- # Start Writing here: -->
<!-- ############################## -->

# Introduction \label{Introduction}
```{r}
#The question has three parts
#1) Compare the SWIX and ALSI (two funds) and then within the ALSI we need to compare rreturns of sectors and cap size
#1) stratefy using the rand and then I want to redo point 1
#3) capping 5%, 10% and uncapped
```
```{r}
# #We can use the rmsfun safe return portfolio if we get the weights
# 
#   sectors<- unique(ALSI$Sector) 
# 
# #for each sector we need to reweight the tickers in each sector
# 
# #Lets find returns for resources first and then we can redo ir for all other sectors and indexes or try and make a function if we have time
# resource_wts <- ALSI %>% 
#     filter(Sector == "Resources") %>% 
#     group_by(date) %>% 
#     mutate(J203 = J203/sum(J203)) %>% #the weights will now sum to 1
#     mutate(J403= J403/sum(J403)) %>% 
#     ungroup() 
# 
# res_rts <- resource_wts %>% 
#     select(date, Tickers, Return)
# #I actually need to separate the weights so we can find the return for both funds
# j2_wts <- resource_wts %>% 
#     select(date, Tickers, J203 ) %>% 
#     spread(Tickers,J203) %>% 
#     tbl_xts()
# j2_wts[is.na(j2_wts)] <- 0
# 
# 
# j4_wts <- resource_wts %>% 
#     select(date, Tickers, J403) %>% 
#     tbl_xts()
# 
# #We need to get the returns for each ticker as well and put it into xts 
# resource_returns <- resource_wts %>% 
#     select(date, Tickers, Return) %>% 
#     spread(Tickers, Return) %>% 
#     tbl_xts()
# resource_returns[is.na(resource_returns)] <- 0 #the function cannot handle NAs
# 
# #?Safe_Return.portfolio    
# j2_resport_rts <- Safe_Return.portfolio(resource_returns, j2_wts, lag_weights = TRUE, contribution = TRUE, verbose = TRUE, value = 1000, geometric = TRUE) 
# 
# j2_res_cont<- 
#     j2_resport_rts$"contribution" %>% xts_tbl()
# 
# j2_res_BPwts<-
#     j2_resport_rts$"BOP.Weight" %>% xts_tbl() 
# 
# j2_resValue <- 
#     j2_resport_rts$BOP.Value %>% xts_tbl() 
# 
# #Let's Bind all of this together
# df_res_rtsj2 <- 
#     left_join(res_rts, j2_res_BPwts %>% gather(Tickers, weights, -date), by = c("date", "Tickers")) %>% 
#     
#     left_join(., j2_resValue %>% gather(Tickers, value_held, -date),
#                 by = c("date", "Tickers") ) %>%  
#     
#     left_join(., j2_res_cont %>%  gather(Tickers, Contribution, -date),
#                 by = c("date", "Tickers"))
# 
# df_j2_resport<- df_res_rtsj2 %>% group_by(date) %>% summarise(Resources = sum(Return*weights, na.rm =TRUE))%>% filter(PortfolioReturn != 0)


    
```

```{r}
#I want to plot the cumulative returns of the J403, J203 and SWIX

#we have the weights so now I just follow the prac 
j403_wts <- ALSI %>% 
    select(date, Tickers, J403) %>% spread(Tickers, J403) %>% tbl_xts()
j403_wts[is.na(j403_wts)] <- 0

j203_wts <- ALSI %>% 
    select(date, Tickers, J203) %>% spread(Tickers, J203) %>% tbl_xts()
j203_wts[is.na(j203_wts)] <- 0


df_Returns <- ALSI %>% 
    select(date, Tickers, Return) %>%  spread(Tickers, Return)
df_Returns[is.na(df_Returns)] <- 0
xts_df_Returns <- df_Returns %>% tbl_xts()

J403_RetPort <- 
      rmsfuns::Safe_Return.portfolio(xts_df_Returns, 
                                     
                       weights = j403_wts, lag_weights = TRUE,
                       
                       verbose = TRUE, contribution = TRUE, 
                       
                       value = 1000, geometric = TRUE) 

    J203_RetPort <- 
      rmsfuns::Safe_Return.portfolio(xts_df_Returns, 
                                     
                       weights = j203_wts, lag_weights = TRUE,
                       
                       verbose = TRUE, contribution = TRUE, 
                       
                       value = 1000, geometric = TRUE) 

# Clean and save portfolio returns and weights:
J403_Contribution <- 
      J403_RetPort$"contribution" %>% xts_tbl() 

J403_BPWeight <- 
  
      J403_RetPort$"BOP.Weight" %>% xts_tbl() 

J403_BPValue <- 
  
     J403_RetPort$"BOP.Value" %>% xts_tbl()  
    
# Clean and save portfolio returns and weights:
J203_Contribution <- 
      J203_RetPort$"contribution" %>% xts_tbl() 

J203_BPWeight <- 
      J203_RetPort$"BOP.Weight" %>% xts_tbl()  

J203_BPValue <- 
      J203_RetPort$"BOP.Value" %>% xts_tbl()
    

    
    # Let's bind all of these together now:
    
    df_port_return_J403 <- 
      left_join(ALSI %>% select(date, Tickers, Return) ,
                J403_BPWeight %>% gather(Tickers, weight, -date),
                by = c("date", "Tickers") ) %>% 
      
      left_join(.,
                J403_BPValue %>% gather(Tickers, value_held, -date),
                by = c("date", "Tickers") ) %>% 
      
      left_join(.,
                J403_Contribution %>% gather(Tickers, Contribution, -date),
                by = c("date", "Tickers"))

    df_port_return_J203 <- 
      left_join(ALSI %>% select(date, Tickers, Return),
                J203_BPWeight %>% gather(Tickers, weight, -date),
                by = c("date", "Tickers") ) %>% 
      
      left_join(.,
               J203_BPValue %>% gather(Tickers, value_held, -date),
                by = c("date", "Tickers") ) %>% 
      
      left_join(.,
                J203_Contribution %>% gather(Tickers, Contribution, -date),
                by = c("date", "Tickers"))

# Calculate Portfolio Returns:
df_Portf_J403 <- 
    df_port_return_J403 %>% group_by(date) %>% summarise(PortfolioReturn = sum(Return*weight, na.rm =TRUE)) %>% 
      filter(PortfolioReturn != 0)
      
# Calculate Portfolio Returns:
df_Portf_J203 <- 
    df_port_return_J203 %>% group_by(date) %>% summarise(PortfolioReturn = sum(Return*weight, na.rm =TRUE)) %>% 
      filter(PortfolioReturn != 0)
#Now lets join the dfs
alsi_rets<-
    left_join(df_Portf_J203 %>% rename("ALSI"= "PortfolioReturn"), df_Portf_J403 %>% rename("SWIX"= "PortfolioReturn"), by = "date") %>% 
    gather(Index, ret, -date)



```

```{r}
#Lets plot them now 
compar_plot<- alsi_rets %>% 
    arrange(date) %>% 
    group_by(Index) %>% 
    mutate(cum_rts = cumprod(1+ret)) %>% 
    select(-ret) %>% 
    ungroup() %>% 
    ggplot()+
    geom_line(aes(date, cum_rts, color = Index))+
    fmxdat::theme_fmx()+
    labs(title = "Cumulative Returns of Both Indexes",  x = "Date", y = "Cumulative Returns")

compar_plot
```

```{r}

#I created a function that filters the data to each sector, adjusts the weight so all the weights of each stock in th sector sum to one (REMEMBER this). then I follow practical 2 where i apply the rmsfun::Safe_Return.portfolio to get the final portfolio returns


#apply the function to all of the sectors for both indexes and then
Resources_j4 <-calculate_portfolio_returns(data = ALSI, sector_name = "Resources", fund_name = "J403") %>% 
    rename("Resources_SWIX"= "PortfolioReturn" )

Financial_j4<- calculate_portfolio_returns(data = ALSI, sector_name = "Financials", fund_name = "J403") %>% 
    rename("Financials_SWIX"= "PortfolioReturn")

Industrials_j4 <- calculate_portfolio_returns(data = ALSI, sector_name = "Industrials", fund_name = "J403") %>% 
    rename("Industrials_SWIX"= "PortfolioReturn")

Property_j4 <-  calculate_portfolio_returns(data = ALSI, sector_name = "Property", fund_name = "J403") %>% 
    rename("Property_SWIX"= "PortfolioReturn")

#now do it again for fund J203
Resources_j2 <-calculate_portfolio_returns(data = ALSI, sector_name = "Resources", fund_name = "J403") %>% 
    rename("Resources_ALSI"= "PortfolioReturn" )

Financial_j2<- calculate_portfolio_returns(data = ALSI, sector_name = "Financials", fund_name = "J403") %>% 
    rename("Financials_ALSI"= "PortfolioReturn")

Industrials_j2 <- calculate_portfolio_returns(data = ALSI, sector_name = "Industrials", fund_name = "J403") %>% 
    rename("Industrials_ALSI"= "PortfolioReturn")

Property_j2 <-  calculate_portfolio_returns(data = ALSI, sector_name = "Property", fund_name = "J403") %>% 
    rename("Property_ALSI"= "PortfolioReturn")   

#Now I just need to join them all together

Sectors_returns_j4 <-
    left_join(Resources_j4, Financial_j4, by = "date") %>% 
    left_join(., Industrials_j4, by ="date") %>% 
    left_join(., Property_j4, by = "date") %>% 
    impute_missing_returns(., impute_returns_method  = "Drawn_Distribution_Own") %>% 
    gather(Sector, ret, -date)

Sectors_returns_j2<- 
     left_join(Resources_j4, Financial_j2, by = "date") %>% 
    left_join(., Industrials_j2, by ="date") %>% 
    left_join(., Property_j2, by = "date")%>% 
     impute_missing_returns(., impute_returns_method  = "Drawn_Distribution_Own") %>% 
    gather(Sector, ret, -date)
   
    
 


```

```{r}
#Now lets plot the cumulative returns for both funds by sector
cum_sectors_j4<- Sectors_returns_j4 %>% 
    arrange(date) %>% 
    group_by(Sector) %>% 
    mutate(cum_rts = cumprod(1+ret)) %>% 
    select(-ret) %>% 
    ungroup() %>% 
    ggplot()+
    geom_line(aes(date, cum_rts, color = Sector))+
    fmxdat::theme_fmx()+
    labs(title = "Cumulative Returns of All Funds", subtitle = "Without fees", x = "Date", y = "Cumulative Returns")

cum_sectors_j4
```

```{r}
cum_sectors_j2<- Sectors_returns_j2 %>% 
    arrange(date) %>% 
    group_by(Sector) %>% 
    mutate(cum_rts = cumprod(1+ret)) %>% 
    select(-ret) %>% 
    ungroup() %>% 
    ggplot()+
    geom_line(aes(date, cum_rts, color = Sector))+
    fmxdat::theme_fmx()+
    labs(title = "Cumulative Returns of All Funds", subtitle = "Without fees", x = "Date", y = "Cumulative Returns")

cum_sectors_j2
```

```{r}
#now lets plot the SWIX and compare
```

```{r}
#I now ammend the previous function so that it filters for the cap rather than sector and then it follows exactly the same process

# caps<- unique(ALSI$Index_Name) 

#follow the same process and get the returns for the different caps
large_j4 <-calculate_portfolio_returns_cap(data = ALSI, cap_name = "Large_Caps", fund_name = "J403") %>% 
    rename("Large_SWIX"= "PortfolioReturn" )

mid_j4 <-calculate_portfolio_returns_cap(data = ALSI, cap_name = "Mid_Caps", fund_name = "J403") %>% 
    rename("Mid_SWIX"= "PortfolioReturn" )

small_j4 <-calculate_portfolio_returns_cap(data = ALSI, cap_name = "Small_Caps", fund_name = "J403") %>% 
    rename("Small_SWIX"= "PortfolioReturn" )

large_j2 <-calculate_portfolio_returns_cap(data = ALSI, cap_name = "Large_Caps", fund_name = "J403") %>% 
    rename("Large_ALSI"= "PortfolioReturn" )

mid_j2 <-calculate_portfolio_returns_cap(data = ALSI, cap_name = "Mid_Caps", fund_name = "J403") %>% 
    rename("Mid_ALSI"= "PortfolioReturn" )

small_j2 <-calculate_portfolio_returns_cap(data = ALSI, cap_name = "Small_Caps", fund_name = "J403") %>% 
    rename("Small_ALSI"= "PortfolioReturn" )


#join each fund
cap_ret_j4 <-
    left_join(large_j4, mid_j4, by = "date") %>% 
    left_join(.,small_j4, by = "date") %>% 
    impute_missing_returns(., impute_returns_method  = "Drawn_Distribution_Own") %>% 
    gather(Cap, ret, -date)

cap_ret_j2 <-
    left_join(large_j2, mid_j2, by = "date") %>% 
    left_join(.,small_j2, by = "date") %>% 
    impute_missing_returns(., impute_returns_method  = "Drawn_Distribution_Own") %>% 
    gather(Cap, ret, -date)

```


```{r}
cum_cap_j4<- cap_ret_j4 %>% 
    arrange(date) %>% 
    group_by(Cap) %>% 
    mutate(cum_rts = cumprod(1+ret)) %>% 
    select(-ret) %>% 
    ungroup() %>% 
    ggplot()+
    geom_line(aes(date, cum_rts, color = Cap))+
    fmxdat::theme_fmx()+
    labs(title = "Cumulative Returns of All Funds", subtitle = "Without fees", x = "Date", y = "Cumulative Returns")

cum_cap_j4
```

```{r}
cum_cap_j2<- cap_ret_j2 %>% 
    arrange(date) %>% 
    group_by(Cap) %>% 
    mutate(cum_rts = cumprod(1+ret)) %>% 
    select(-ret) %>% 
    ungroup() %>% 
    ggplot()+
    geom_line(aes(date, cum_rts, color = Cap))+
    fmxdat::theme_fmx()+
    labs(title = "Cumulative Returns of All Funds", subtitle = "Without fees", x = "Date", y = "Cumulative Returns")

cum_cap_j2
```
# Stratification
```{r}
Idxs <- alsi_rets

Idxs <-
  
  Idxs %>% 
    mutate(Year = format(date, "%Y")) %>% 
    
    group_by(Index) %>% 
  
  mutate(Top = quantile(ret, 0.99), Bot = quantile(ret, 0.01)) %>% 
  
  mutate(ret = ifelse(ret > Top, Top, 
                         
                         ifelse(ret < Bot, Bot, ret))) %>% ungroup()

ZARSD <- ZAR %>% 
    filter(date>lubridate::ymd(20130101)) %>% #to match the index data
    mutate(Year = format(date, "%Y")) %>% #unlike the prac we have montly data so we need to look at yearly rather
    arrange(date) %>% 
    mutate(Return= value/lag(value)-1) %>% 
  
  group_by(Year) %>% summarise(SD = sd(Return)*sqrt(12)) %>% 
  
  # Top Decile Quantile overall (highly volatile month for ZAR:
  mutate(TopQtile = quantile(SD, 0.8, na.rm = TRUE),
         
         BotQtile = quantile(SD, 0.2, na.rm = TRUE))



Hi_Vol <- ZARSD %>% filter(SD > TopQtile) %>% pull(Year)

Low_Vol <- ZARSD %>% filter(SD < BotQtile) %>% pull(Year)

Perf_comparisons <- function(Idxs, Ys, Alias){
  # For stepping through uncomment:
  # YMs <- Hi_Vol
  Unconditional_SD <- 
    
  Idxs %>% 
    
    group_by(Index) %>% 
    
    mutate(Full_SD = sd(ret) * sqrt(12)) %>% 
    
    filter(Year %in% Ys) %>% 
    
    summarise(SD = sd(ret) * sqrt(12), across(.cols = starts_with("Full"), .fns = max)) %>% 
    
    arrange(desc(SD)) %>% mutate(Period = Alias) %>% 
    
    group_by(Index) %>% 
    
    mutate(Ratio = SD / Full_SD)
    
    Unconditional_SD
  
}

perf_hi <- Perf_comparisons(Idxs, Ys = Hi_Vol, Alias = "High_Vol")

perf_lo <- Perf_comparisons(Idxs, Ys = Low_Vol, Alias = "Low_Vol")

kableExtra::kable(perf_hi)
```

```{r}
kableExtra::kable(perf_lo)
```

# Capping
```{r}
#Let's follow the extra prac 1 for this 
#start with J403
Rebalance_days <- RebDays %>% 
    filter(Date_Type == "Reb Trade Day") %>% # only concerned on the day that we are actually rebalancing
    pull(date)

rebalance_col <- ALSI %>%
    rename("weight"= "J403") %>% #the functions use weight so this makes it easier for me later on
    filter(date %in% Rebalance_days ) %>% 
    mutate(RebalanceTime = format(date, "%Y%B%A")) %>% 
    group_by(RebalanceTime) %>% 
    arrange(desc(weight)) %>% 
    ungroup() %>% 
    arrange(date) %>% 
    select(date, Tickers, weight, RebalanceTime )

# df_Cons <- rebalance_col %>% filter(date == first(date))
#  W_Cap = 0.8
  

# Now, to map this across all the dates, we can use purrr::map_df as follows:
  Capped_df <- 
    
    rebalance_col %>% 
    # Split our df into groups (where the groups here are the rebalance dates:
    group_split(RebalanceTime) %>% 
    
    # Apply the function Proportional_Cap_Foo to each rebalancing date:
    map_df(~Proportional_Cap_Foo(., W_Cap = 0.08) ) %>% select(-RebalanceTime)
    

wts<-
    Capped_df %>% 
    tbl_xts(cols_to_xts = weight, spread_by = Tickers)

rts <- ALSI %>% 
    filter(Tickers %in% unique(Capped_df$Tickers) ) %>% 
  
  tbl_xts(cols_to_xts = Return, spread_by = Tickers)

wts[is.na(wts)] <- 0

rts[is.na(rts)] <- 0

Idx <- 
  rmsfuns::Safe_Return.portfolio(R = rts, weights = wts, lag_weights = T) %>% 
  
  # Let's make this a tibble:
  xts_tbl() %>% 
  
  rename("J403" = "portfolio.returns")



```


```{r}
#Function
library(tidyverse)
library(rmsfuns)

rebalance_and_calculate_returns <- function(data, fund_name, w_cap) {
  rebalance_col <- data %>%
    rename("weight" = {{ fund_name }}) %>%
    filter(date %in% Rebalance_days) %>%
    mutate(RebalanceTime = format(date, "%Y%B%A")) %>%
    group_by(RebalanceTime) %>%
    arrange(desc(weight)) %>%
    ungroup() %>%
    arrange(date) %>%
    select(date, Tickers, weight, RebalanceTime)

  # df_Cons <- rebalance_col %>% filter(date == first(date))
  # W_Cap = 0.8
Proportional_Cap_Foo <- function(df_Cons, W_Cap = 0.05){

    # Let's require a specific form from the user... Alerting when it does not adhere this form
    if( !"weight" %in% names(df_Cons)) stop("... for Calc capping to work, provide weight column called 'weight'")

    if( !"date" %in% names(df_Cons)) stop("... for Calc capping to work, provide date column called 'date'")

    if( !"Tickers" %in% names(df_Cons)) stop("... for Calc capping to work, provide id column called 'Tickers'")

    # First identify the cap breachers...
    Breachers <-
        df_Cons %>% filter(weight > W_Cap) %>% pull(Tickers)

    # Now keep track of breachers, and add to it to ensure they remain at 10%:
    if(length(Breachers) > 0) {

        while( df_Cons %>% filter(weight > W_Cap) %>% nrow() > 0 ) {


            df_Cons <-

                bind_rows(

                    df_Cons %>% filter(Tickers %in% Breachers) %>% mutate(weight = W_Cap),

                    df_Cons %>% filter(!Tickers %in% Breachers) %>%
                        mutate(weight = (weight / sum(weight, na.rm=T)) * (1-length(Breachers)*W_Cap) )

                )

            Breachers <- c(Breachers, df_Cons %>% filter(weight > W_Cap) %>% pull(Tickers))

        }

        if( sum(df_Cons$weight, na.rm=T) > 1.001 | sum(df_Cons$weight, na.rm=T) < 0.999 | max(df_Cons$weight, na.rm = T) > W_Cap) {

            stop( glue::glue("For the Generic weight trimming function used: the weight trimming causes non unit
      summation of weights for date: {unique(df_Cons$date)}...\n
      The restriction could be too low or some dates have extreme concentrations...") )

        }

    } else {

    }

    df_Cons

}
  # Now, to map this across all the dates, we can use purrr::map_df as follows:
  Capped_df <- rebalance_col %>%
    # Split our df into groups (where the groups here are the rebalance dates:
    group_split(RebalanceTime) %>%
    # Apply the function Proportional_Cap_Foo to each rebalancing date:
    map_df(~Proportional_Cap_Foo(., W_Cap = w_cap)) %>% select(-RebalanceTime)

  wts <- Capped_df %>%
    tbl_xts(cols_to_xts = weight, spread_by = Tickers)

  rts <- data %>%
    filter(Tickers %in% unique(Capped_df$Tickers)) %>%
    tbl_xts(cols_to_xts = Return, spread_by = Tickers)

  wts[is.na(wts)] <- 0
  rts[is.na(rts)] <- 0

  Idx <- rmsfuns::Safe_Return.portfolio(R = rts, weights = wts, lag_weights = TRUE) %>%
    # Let's make this a tibble:
    xts_tbl() %>%
    rename({{ fund_name }} := "portfolio.returns")

  return(Idx)
}

#now use the function to get the returns and get ready to "plot this bugga"
alsi_5 <- rebalance_and_calculate_returns(ALSI, J203, w_cap = 0.05) %>% 
    rename("ALSI"= "J203") %>% 
    mutate(Index = "5%")

alsi_10 <- rebalance_and_calculate_returns(ALSI, J203, w_cap = 0.10) %>% 
    rename("ALSI"= "J203") %>% 
    mutate(Index = "10%")

alsi_un <- rebalance_and_calculate_returns(ALSI, J203, w_cap = 1) %>% 
    rename("ALSI"= "J203") %>% 
    mutate(Index = "No Cap")

swix_5 <- rebalance_and_calculate_returns(ALSI, J403, w_cap = 0.05) %>% 
    rename("SWIX"= "J403") %>% 
    mutate(Index = "5%")

swix_10 <- rebalance_and_calculate_returns(ALSI, J403, w_cap = 0.1) %>% 
    rename("SWIX"= "J403") %>% 
    mutate(Index = "10%")

swix_un <- rebalance_and_calculate_returns(ALSI, J403, w_cap = 1) %>% 
    rename("SWIX"= "J403") %>% 
    mutate(Index = "No Cap")


# Combine ALSI data frames
alsi_combined <- bind_rows(
  alsi_5 %>% select(date, ALSI, Index),
  alsi_10 %>% select(date, ALSI, Index),
  alsi_un %>% select(date, ALSI, Index)
)

# Combine SWIX data frames
swix_combined <- bind_rows(
  swix_5 %>% select(date, SWIX, Index),
  swix_10 %>% select(date, SWIX, Index),
  swix_un %>% select(date, SWIX, Index)
)

# Merge ALSI and SWIX data frames based on the "date" column
idx <- full_join(alsi_combined, swix_combined, by = c("date","Index")) %>% 
    select(date, SWIX, ALSI, Index)


```

```{r}
# Let's plot this bugger
idx %>% 
  mutate(swix = cumprod(1+SWIX)) %>% 
    mutate(alsi = cumprod(1+ALSI)) %>% 
  
  ggplot(., aes(x = date)) +
  geom_line(aes(y = alsi, color = "ALSI"), size = 1) +
  geom_line(aes(y = swix, color = "SWIX"), size = 1) +
  facet_wrap(~Index, scales = "free_y", ncol = 1) +
  labs(title = "ALSI and SWIX Over Time", x = "Date", y = "Value") +
  scale_color_manual(values = c(ALSI = "blue", SWIX = "red"))+
    theme_fmx()
```

\newpage

# References {-}

<div id="refs"></div>



